const CHIFF =[
    {
        id:1,
        title:"Chiffon Floral Printed Saree",
        price:1560,
        image:"/images/chiffon/chiffon.webp", 
        colors:[
            "Red",
            "Blue",
            "Orange",
            "Green",
            "Yellow",
        ],
        sizes:[
            "S",
            "M",
            "L",
            "XL",
            "XXL",
            "XXXL",
        ],
      
          quantity:[
            "1","2","3","4","5"
        ],
        stars:"4.4"
    },
    {
        id:2,
        title:"Wine Purple Chiffon Satin Saree",
        price:2365,
        image:"/images/chiffon/chiffon2.webp",
        colors:[
            "Red",
            "Blue",
            "Orange",
            "Green",
            "Yellow",
        ],
        sizes:[
            "S",
            "M",
            "L",
            "XL",
            "XXL",
            "XXXL",
        ],
          quantity:[
            "1","2","3","4","5"
        ],
        stars:"4.5"
    },
    {
        id:3,
        title:"Yellow Chiffon Georgette Woven Saree",
        price:1620,
        image:"/images/chiffon/chiffon3.webp",
        colors:[
            "Red",
            "Blue",
            "Orange",
            "Green",
            "Yellow",
        ],
        sizes:[
            "S",
            "M",
            "L",
            "XL",
            "XXL",
            "XXXL",
        ],
          quantity:[
            "1","2","3","4","5"
        ],
        stars:"3.4"
    },
    {
        id:4,
        title:"Chitrangada Singh Light Pink Chiffon Georgette Printed Saree",
        price:1950,
        image:"/images/chiffon/chiffon4.webp",
        colors:[
            "Red",
            "Blue",
            "Orange",
            "Green",
            "Yellow",
        ],
        sizes:[
            "S",
            "M",
            "L",
            "XL",
            "XXL",
            "XXXL",
        ],
          quantity:[
            "1","2","3","4","5"
        ],
        stars:"3.7"
    },
    {
        id:5,
        title:"Red Chiffon Sequins Work Saree",
        price:3530,
        image:"/images/chiffon/chiffon5.webp",
        colors:[
            "Red",
            "Blue",
            "Orange",
            "Green",
            "Yellow",
        ],
        sizes:[
            "S",
            "M",
            "L",
            "XL",
            "XXL",
            "XXXL",
        ],
          quantity:[
            "1","2","3","4","5"
        ],
        stars:"3.5"
    },
    {
        id:6,
        title:"Grey and Black Chiffon Saree with Sequins Border",
        price:3640,
        image:"/images/chiffon/chiffon6.webp",
        colors:[
            "Red",
            "Blue",
            "Orange",
            "Green",
            "Yellow",
        ],
        sizes:[
            "S",
            "M",
            "L",
            "XL",
            "XXL",
            "XXXL",
        ],
          quantity:[
            "1","2","3","4","5"
        ],
        stars:"4.3"
    },
    {
        id:7,
        title:"Maroon and Orange Georgette Bandhani Printed Saree",
        price:1510,
        image:"/images/chiffon/chiffon7.webp",
        colors:[
            "Red",
            "Blue",
            "Orange",
            "Green",
            "Yellow",
        ],
        sizes:[
            "S",
            "M",
            "L",
            "XL",
            "XXL",
            "XXXL",
        ],
        quantity:[
            "1","2","3","4","5"
        ],
        stars:"3.4"
    },
    {
        id:8,
        title:"Peach Chiffon Shimmer Saree with Embroidery",
        price:3485,
        image:"/images/chiffon/chiffon8.webp",
        colors:[
            "Red",
            "Blue",
            "Orange",
            "Green",
            "Yellow",
        ],
        sizes:[
            "S",
            "M",
            "L",
            "XL",
            "XXL",
            "XXXL",
        ],
          quantity:[
            "1","2","3","4","5"
        ],
        stars:"3.8"
    },
    {
        id:9,
        title:"Light Blue Chiffon Saree with Embroidered Lace",
        price:2485,
        image:"/images/chiffon/chiffon9.webp",
        colors:[
            "Red",
            "Blue",
            "Orange",
            "Green",
            "Yellow",
        ],
        sizes:[
            "S",
            "M",
            "L",
            "XL",
            "XXL",
            "XXXL",
        ],
          quantity:[
            "1","2","3","4","5"
        ],
        stars:"3.8"
    },
]

export default CHIFF